function stateColumns(prefix: string): string[] {
  return [
    "inning",
    "half",
    "half_active",
    "balls",
    "strikes",
    "outs",
    "base1_runner_id",
    "base1_pitcher_id",
    "base2_runner_id",
    "base2_pitcher_id",
    "base3_runner_id",
    "base3_pitcher_id",
    "away_score",
    "home_score",
    "batter_id",
    "pitcher_id",
    "active_away_pitcher_id",
    "active_home_pitcher_id",
    "pa_start_event_id",
    "pa_start_batter_id",
    "pa_start_pitcher_id",
    "pa_walk_responsible_pitcher_id",
    "pa_strikeout_responsible_batter_id",
    "pa_actual_pitch_count",
  ].map((column) => `${prefix}_${column}`);
}

function pitchStateColumns(prefix: string): string[] {
  return [
    `${prefix}_balls`,
    `${prefix}_strikes`,
    `${prefix}_outs`,
    `${prefix}_base1_runner_id`,
    `${prefix}_base2_runner_id`,
    `${prefix}_base3_runner_id`,
    `${prefix}_away_score`,
    `${prefix}_home_score`,
  ];
}

export const PROJECTION_TABLE_COLUMNS = {
  game_team_snapshots: ["game_id", "revision", "side", "team_id", "team_name"],
  game_roster_snapshots: [
    "game_id",
    "revision",
    "side",
    "roster_index",
    "player_id",
    "player_name",
    "batting_order",
    "starter",
  ],
  game_roster_positions: [
    "game_id",
    "revision",
    "side",
    "roster_index",
    "position_index",
    "position",
  ],
  relay_event_facts: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "identity_kind",
    "source_endpoint",
    "source_block_index",
    "source_event_index",
    "source_event_id",
    "kind",
    "inning",
    "half",
    "relay_text",
    "observed_balls",
    "observed_strikes",
    "observed_outs",
    "observed_base1",
    "observed_base2",
    "observed_base3",
    "observed_away_score",
    "observed_home_score",
  ],
  relay_half_inning_starts: ["game_id", "revision", "event_sequence", "event_id", "kind"],
  relay_batter_starts: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "batter_id",
    "pitcher_id",
  ],
  relay_pitches: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "source_pitch_id",
    "pitch_call",
    "batter_id",
    "pitcher_id",
  ],
  relay_plate_results: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "plate_result",
    "batter_id",
    "pitcher_id",
    "credited_rbi",
    "outs_recorded",
    "batter_destination",
    "batted_ball_type",
    "is_bunt",
  ],
  relay_runner_advances: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "runner_id",
    "from_base",
    "to_base",
    "runner_outcome",
    "runner_out_kind",
    "supersedes_third_out",
    "responsible_pitcher_id",
    "runner_context_kind",
    "plate_result_event_id",
    "runner_reason",
  ],
  relay_substitutions: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "substitution_side",
    "substitution_role",
    "incoming_player_id",
    "outgoing_player_id",
    "batting_order",
    "field_position",
  ],
  relay_reviews: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "review_decision",
    "reviewed_event_id",
  ],
  relay_administrative: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "administrative_code",
  ],
  relay_unresolved: [
    "game_id",
    "revision",
    "event_sequence",
    "event_id",
    "kind",
    "unresolved_source_type",
    "suspected_kind",
  ],
  tracking_observations: [
    "game_id",
    "revision",
    "tracking_sequence",
    "tracking_id",
    "measurement_profile_id",
    "source_pitch_id",
    "source_pitch_ordinal",
    "source_endpoint",
    "source_block_index",
    "source_row_index",
    "inning",
    "half",
    "plate_appearance_event_id",
    "pitcher_id",
    "batter_id",
    "observed_at",
    "stance",
    "x0",
    "y0",
    "z0",
    "vx0",
    "vy0",
    "vz0",
    "ax",
    "ay",
    "az",
    "cross_plate_x",
    "cross_plate_y",
    "top_sz",
    "bottom_sz",
    "resolution_kind",
    "pitch_event_id",
    "canonical_tracking_id",
    "exclusion_reason",
    "exclusion_note",
  ],
  pitch_facts: [
    "game_id",
    "revision",
    "pitch_sequence",
    "pitch_id",
    "plate_appearance_event_id",
    "pitch_event_number",
    "actual_pitch_number",
    "inning",
    "half",
    "batter_id",
    "pitcher_id",
    "source_pitch_id",
    "pitch_call",
    "actual",
    "ball",
    "called_strike",
    "swing",
    "whiff",
    "foul",
    "in_play",
    "strike",
    "csw",
    ...pitchStateColumns("before"),
    ...pitchStateColumns("after"),
  ],
  pitch_tracking_links: ["game_id", "revision", "tracking_sequence", "pitch_id", "tracking_id"],
  official_batter_lines: [
    "game_id",
    "revision",
    "record_index",
    "player_id",
    "side",
    "plate_appearances",
    "at_bats",
    "runs",
    "hits",
    "doubles",
    "triples",
    "home_runs",
    "runs_batted_in",
    "walks",
    "intentional_walks",
    "hit_by_pitch",
    "strikeouts",
    "sacrifice_bunts",
    "sacrifice_flies",
  ],
  official_pitcher_lines: [
    "game_id",
    "revision",
    "record_index",
    "player_id",
    "side",
    "batters_faced",
    "outs_recorded",
    "hits",
    "runs",
    "earned_runs",
    "walks",
    "intentional_walks",
    "hit_by_pitch",
    "strikeouts",
    "pitches",
    "strikes",
  ],
  play_facts: [
    "game_id",
    "revision",
    "play_sequence",
    "play_id",
    "source_sequence",
    "kind",
    "inning",
    "half",
    "applied",
    ...stateColumns("before"),
    ...stateColumns("after"),
  ],
  play_events: [
    "game_id",
    "revision",
    "play_sequence",
    "relay_order",
    "event_sequence",
    "event_id",
    "relay_text",
  ],
  runner_movement_facts: [
    "game_id",
    "revision",
    "play_sequence",
    "movement_sequence",
    "movement_id",
    "source_event_id",
    "source_sequence",
    "runner_id",
    "from_base",
    "to_base",
    "outcome",
    "out_kind",
    "supersedes_third_out",
    "responsible_pitcher_id",
    "reason",
    "derived",
  ],
  game_final_states: ["game_id", "revision", ...stateColumns("final")],
  plate_appearance_facts: [
    "game_id",
    "revision",
    "plate_appearance_index",
    "start_event_id",
    "end_event_id",
    "inning",
    "half",
    "start_batter_id",
    "batter_id",
    "start_pitcher_id",
    "pitcher_id",
    "result",
    "batted_ball_type",
    "is_bunt",
    "completed",
    "termination_reason",
    "actual_pitch_count",
    "counts_as_plate_appearance",
    "counts_as_at_bat",
    "counts_as_batter_faced",
  ],
  plate_appearance_events: [
    "game_id",
    "revision",
    "plate_appearance_index",
    "event_number",
    "event_id",
    "event_sequence",
    "pitch_event_number",
    "pitch_number",
  ],
  batter_game_facts: [
    "game_id",
    "revision",
    "line_index",
    "player_id",
    "side",
    "plate_appearances",
    "at_bats",
    "runs",
    "hits",
    "doubles",
    "triples",
    "home_runs",
    "runs_batted_in",
    "walks",
    "intentional_walks",
    "hit_by_pitch",
    "strikeouts",
    "sacrifice_bunts",
    "sacrifice_flies",
  ],
  pitcher_game_facts: [
    "game_id",
    "revision",
    "line_index",
    "player_id",
    "side",
    "batters_faced",
    "outs_recorded",
    "hits",
    "runs",
    "official_earned_runs",
    "walks",
    "intentional_walks",
    "hit_by_pitch",
    "strikeouts",
    "pitches",
    "strikes",
  ],
  baserunner_game_facts: [
    "game_id",
    "revision",
    "line_index",
    "player_id",
    "side",
    "advances",
    "extra_bases_taken",
    "runs",
    "stolen_bases",
    "caught_stealing",
    "pickoffs",
  ],
  validation_runs: ["game_id", "revision", "blocking_count", "warning_count", "issue_count"],
  validation_issues: [
    "game_id",
    "revision",
    "issue_index",
    "code",
    "category",
    "severity",
    "message",
    "event_id",
    "event_sequence",
    "record_identity",
  ],
  validation_issue_details: [
    "game_id",
    "revision",
    "issue_index",
    "detail_index",
    "field",
    "expected_type",
    "expected_text",
    "expected_number",
    "expected_boolean",
    "actual_type",
    "actual_text",
    "actual_number",
    "actual_boolean",
  ],
} as const;

export type ProjectionTableName = keyof typeof PROJECTION_TABLE_COLUMNS;

const PROJECTION_TABLE_ORDER: Readonly<Record<ProjectionTableName, string>> = {
  game_team_snapshots: "side",
  game_roster_snapshots: "side, roster_index",
  game_roster_positions: "side, roster_index, position_index",
  relay_event_facts: "event_sequence",
  relay_half_inning_starts: "event_sequence",
  relay_batter_starts: "event_sequence",
  relay_pitches: "event_sequence",
  relay_plate_results: "event_sequence",
  relay_runner_advances: "event_sequence",
  relay_substitutions: "event_sequence",
  relay_reviews: "event_sequence",
  relay_administrative: "event_sequence",
  relay_unresolved: "event_sequence",
  tracking_observations: "tracking_sequence",
  pitch_facts: "pitch_sequence",
  pitch_tracking_links: "tracking_sequence",
  official_batter_lines: "record_index",
  official_pitcher_lines: "record_index",
  play_facts: "play_sequence",
  play_events: "play_sequence, relay_order",
  runner_movement_facts: "play_sequence, movement_sequence",
  game_final_states: "game_id",
  plate_appearance_facts: "plate_appearance_index",
  plate_appearance_events: "plate_appearance_index, event_number",
  batter_game_facts: "line_index",
  pitcher_game_facts: "line_index",
  baserunner_game_facts: "line_index",
  validation_runs: "game_id",
  validation_issues: "issue_index",
  validation_issue_details: "issue_index, detail_index",
};

export interface ProjectionTableDescriptor<Name extends ProjectionTableName = ProjectionTableName> {
  readonly name: Name;
  readonly schema: "workbench" | "baseball";
  readonly columns: (typeof PROJECTION_TABLE_COLUMNS)[Name];
  readonly orderBy: string;
}

export const PROJECTION_TABLE_DESCRIPTORS = (
  Object.keys(PROJECTION_TABLE_COLUMNS) as ProjectionTableName[]
).map((name): ProjectionTableDescriptor => ({
  name,
  schema: [
    "game_team_snapshots",
    "game_roster_snapshots",
    "game_roster_positions",
    "relay_event_facts",
    "relay_half_inning_starts",
    "relay_batter_starts",
    "relay_pitches",
    "relay_plate_results",
    "relay_runner_advances",
    "relay_substitutions",
    "relay_reviews",
    "relay_administrative",
    "relay_unresolved",
    "tracking_observations",
    "official_batter_lines",
    "official_pitcher_lines",
    "validation_runs",
    "validation_issues",
    "validation_issue_details",
  ].includes(name)
    ? "workbench"
    : "baseball",
  columns: PROJECTION_TABLE_COLUMNS[name],
  orderBy: PROJECTION_TABLE_ORDER[name],
}));
