import type { BattingStatisticsTotals, PitchingStatisticsTotals } from "@kbo/contracts";
export const battingTotals: BattingStatisticsTotals = {
  identity: "naver:a1",
  playerId: "a1",
  name: "타자 A",
  teamId: "AWAY",
  teamName: "원정",
  games: 2,
  plateAppearances: 8,
  atBats: 5,
  hits: 2,
  doubles: 1,
  triples: 0,
  homeRuns: 1,
  walks: 1,
  intentionalWalks: 1,
  hitByPitch: 1,
  strikeouts: 1,
  sacrificeFlies: 1,
  sacrificeBunts: 0,
  runs: 2,
};
export const pitchingTotals: PitchingStatisticsTotals = {
  identity: "naver:hp1",
  playerId: "hp1",
  name: "투수 A",
  teamId: "HOME",
  teamName: "홈",
  games: 2,
  battersFaced: 40,
  outsRecorded: 27,
  hits: 8,
  runs: 3,
  walks: 2,
  intentionalWalks: 1,
  hitByPitch: 0,
  strikeouts: 8,
  pitches: 150,
  strikes: 100,
  knownErGames: 1,
  knownErOuts: 9,
  knownEarnedRuns: 1,
};
